name: Pipeline-P1

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del c√≥digo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Login en DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. Build de la imagen
      - name: Build Docker image
        run: |
          docker build -t drearchino624/ld-demo:latest ./app

      # 4. Push de la imagen
      - name: Push Docker image
        run: |
          docker push drearchino624/ld-demo:latest

      # 5. (Opcional) Ac
